Repository iotaledger/trinity-wallet, pull requests merged in 2020-09, with the labels that each got.

#3016 feature(ci): Allow desktop releases to be rolled back
  .github/workflows/build_desktop.yml
  .github/workflows/rollback_desktop.yml
Labels: T - Meta

#3024 feature(ci): Use prebuilt OpenSSL for Windows builds
  .github/workflows/build_desktop.yml
Labels: T - Meta

#3027 feature(ci): Run desktop tests on macOS, temp disable Linux
  .github/workflows/test_desktop.yml
Labels: T - Meta

#3020 fix: avoid incrementing step counter on retry
  src/shared/actions/transfers.js
Labels: C - Shared, T - Bug

#3032 fix: ensure polling starts with promotion
  src/desktop/src/ui/Index.js
  src/desktop/src/ui/views/onboarding/Login.js
  src/mobile/src/ui/routes/entry.js
  src/mobile/src/ui/views/wallet/Loading.js
  src/shared/actions/polling.js
  src/shared/reducers/polling.js
Labels: C - Desktop, C - Mobile, C - Shared, T - Bug

#3029 fix(shared): autopromotion improvements
  src/desktop/src/ui/global/Polling.js
  src/mobile/src/ui/components/Poll.js
  src/shared/actions/polling.js
  src/shared/actions/transfers.js
  src/shared/libs/iota/extendedApi.js
  src/shared/libs/iota/transfers.js
  src/shared/selectors/accounts.js
Labels: C - Desktop, C - Mobile, C - Shared, T - Bug, T - Enhancement

#3039 chore(desktop): update 1.6.1 changelog
  src/desktop/CHANGELOG.md
Labels: C - Desktop

#3036 feature(ci): Adding basic codeQL scannning to the repo.
  .github/workflows/codeql-analysis.yml
Labels: T - Meta

#3043 fix(ci) Public read access on new binaries uploads
  .github/workflows/build_desktop.yml
Labels: T - Meta

#3044 fix(desktop/linux): Show OK button on update message box
  src/desktop/native/libs/Menu.js
Labels: C - Desktop, P - Linux, T - Bug

#3045 chore(desktop): update changelog
  src/desktop/CHANGELOG.md
Labels: C - Desktop

#3042 chore(desktop): update version to 1.6.1
  src/shared/libs/versions.json
Labels: L - Do not merge

#3041 feature(ci): Enable security-and-quality QL pack
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: T - Meta
